### PR TITLE
decoder: add support for decoding floats

### PR DESCRIPTION
**Pull request by benpicco**
This adds the patch from @MBradbury to include float support in the decoder. 

alternative to #25

### CODE REVIEW

**Comment by MBradbury** [comment]
My only concern is that my commit simply copied the half-precision float support as quick fix for my own project. It might be worth asking if QCBOR's author would be willing to spin that out into its own repository, so NanoCBOR could include it as a submodule.

I imagine there should also be configuration macros to disable float support.

**Comment by bergzand** [comment]
If float decoding is a feature needed in NanoCBOR, I'm fine with working on it for a day and getting an implementation without license conflicts :)

**Comment by MBradbury** [comment]
I did have a quick look and BSD-3 seems compatible with LGPL 2.1 (https://www.gnu.org/licenses/license-list.en.html#ModifiedBSD), but then I suppose it would complicate the licence of NanoCBOR as it becomes dual LGPL 2.1 and BSD-3.

**Comment by bergzand** [comment]
> I did have a quick look and BSD-3 seems compatible with LGPL 2.1 (https://www.gnu.org/licenses/license-list.en.html#ModifiedBSD), but then I suppose it would complicate the licence of NanoCBOR as it becomes dual LGPL 2.1 and BSD-3.

I have some plans to relicense NanoCBOR to public domain (no time so far to actually commit it).

**Comment by bergzand** [comment]
With #65 merged there is now support for decoding floats and doubles.

**Pull request closed without merging**
